### ISSUE TITLE
Cannot establish embassies with minor factions

### ISSUE THREAD

**Issue by raixdawolf** [GoaFan77/Enhanced4XModRepo#12]
When sending an envoy ship to establish an embassy with a minor faction, an error is issued indicating that this ability can only be used on friendly targets. No embassy is established and you are effectively locked out of using minor factions to your advantage.

This is likely due to something within the conditional logic regarding what targets an envoy can used the ability establish embassy on. An exception should be made specifically for minor factions, though logic may need to be included for players with certain relationships. An example of this would be from Civilization, where City States will refuse to deal with a player if they have showed aggression towards other City States in the past.

It is currently unknown if the Goodwill ability from the base game is available on embassies. A quick fix may involve allowing envoys to used this ability again.

**Comment by pmaher478** [comment]
This issue is fixed by commit d5e807e8007706c5f51d11dcdd9cbcfdf6cdc0f9

**Comment by raixdawolf** [comment]
It appears to work on some worlds and not on others. Will investigate further.

**Comment by GoaFan77** [comment]
@raixdawolf Please let us know. We are currently updating the mod for the new minor factions DLC. If you have pulled the latest build from github and are having issues with capturing minor factions, we will reopen this issue.

Note there is a bug with the mods original "random encounter" factions causing strange militia owned worlds to spawn. These are not minor factions so that might explain why its not working on some worlds.

**Comment by raixdawolf** [comment]
@GoaFan77 I think that is all it was. Once we got it working, we figured this was the problem. Thank you and @pmaher478 for getting back on the issue.
